/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as AuthTanstackSseTestRouteImport } from './routes/_auth/tanstack-sse-test'
import { Route as AuthGovernanceRouteImport } from './routes/_auth/governance'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthUsersIndexRouteImport } from './routes/_auth/users/index'
import { Route as AuthRolesIndexRouteImport } from './routes/_auth/roles/index'
import { Route as AuthProvidersIndexRouteImport } from './routes/_auth/providers/index'
import { Route as AuthChannelsIndexRouteImport } from './routes/_auth/channels/index'
import { Route as AuthAgentsIndexRouteImport } from './routes/_auth/agents/index'
import { Route as AuthAgentTeamsIndexRouteImport } from './routes/_auth/agent-teams/index'
import { Route as AuthUsersCreateRouteImport } from './routes/_auth/users/create'
import { Route as AuthProvidersCreateRouteImport } from './routes/_auth/providers/create'
import { Route as AuthChannelsCreateRouteImport } from './routes/_auth/channels/create'
import { Route as AuthAgentsCreateRouteImport } from './routes/_auth/agents/create'
import { Route as AuthAgentTeamsCreateRouteImport } from './routes/_auth/agent-teams/create'
import { Route as AuthLlmSkillsIndexRouteImport } from './routes/_auth/llm/skills/index'
import { Route as AuthUsersUserIdEditRouteImport } from './routes/_auth/users/$userId/edit'
import { Route as AuthProvidersProviderIdEditRouteImport } from './routes/_auth/providers/$providerId/edit'
import { Route as AuthLlmSkillsCreateRouteImport } from './routes/_auth/llm/skills/create'
import { Route as AuthChannelsChannelIdEditRouteImport } from './routes/_auth/channels/$channelId/edit'
import { Route as AuthAgentsAgentIdEditRouteImport } from './routes/_auth/agents/$agentId/edit'
import { Route as AuthAgentTeamsTeamIdEditRouteImport } from './routes/_auth/agent-teams/$teamId/edit'
import { Route as AuthLlmSkillsSkillIdEditRouteImport } from './routes/_auth/llm/skills/$skillId/edit'

const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)
const AuthTanstackSseTestRoute = AuthTanstackSseTestRouteImport.update({
  id: '/tanstack-sse-test',
  path: '/tanstack-sse-test',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGovernanceRoute = AuthGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersIndexRoute = AuthUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRolesIndexRoute = AuthRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProvidersIndexRoute = AuthProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChannelsIndexRoute = AuthChannelsIndexRouteImport.update({
  id: '/channels/',
  path: '/channels/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAgentsIndexRoute = AuthAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAgentTeamsIndexRoute = AuthAgentTeamsIndexRouteImport.update({
  id: '/agent-teams/',
  path: '/agent-teams/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersCreateRoute = AuthUsersCreateRouteImport.update({
  id: '/users/create',
  path: '/users/create',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProvidersCreateRoute = AuthProvidersCreateRouteImport.update({
  id: '/providers/create',
  path: '/providers/create',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChannelsCreateRoute = AuthChannelsCreateRouteImport.update({
  id: '/channels/create',
  path: '/channels/create',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAgentsCreateRoute = AuthAgentsCreateRouteImport.update({
  id: '/agents/create',
  path: '/agents/create',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAgentTeamsCreateRoute = AuthAgentTeamsCreateRouteImport.update({
  id: '/agent-teams/create',
  path: '/agent-teams/create',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLlmSkillsIndexRoute = AuthLlmSkillsIndexRouteImport.update({
  id: '/llm/skills/',
  path: '/llm/skills/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersUserIdEditRoute = AuthUsersUserIdEditRouteImport.update({
  id: '/users/$userId/edit',
  path: '/users/$userId/edit',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProvidersProviderIdEditRoute =
  AuthProvidersProviderIdEditRouteImport.update({
    id: '/providers/$providerId/edit',
    path: '/providers/$providerId/edit',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthLlmSkillsCreateRoute = AuthLlmSkillsCreateRouteImport.update({
  id: '/llm/skills/create',
  path: '/llm/skills/create',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChannelsChannelIdEditRoute =
  AuthChannelsChannelIdEditRouteImport.update({
    id: '/channels/$channelId/edit',
    path: '/channels/$channelId/edit',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthAgentsAgentIdEditRoute = AuthAgentsAgentIdEditRouteImport.update({
  id: '/agents/$agentId/edit',
  path: '/agents/$agentId/edit',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAgentTeamsTeamIdEditRoute =
  AuthAgentTeamsTeamIdEditRouteImport.update({
    id: '/agent-teams/$teamId/edit',
    path: '/agent-teams/$teamId/edit',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthLlmSkillsSkillIdEditRoute =
  AuthLlmSkillsSkillIdEditRouteImport.update({
    id: '/llm/skills/$skillId/edit',
    path: '/llm/skills/$skillId/edit',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthDashboardRoute
  '/governance': typeof AuthGovernanceRoute
  '/tanstack-sse-test': typeof AuthTanstackSseTestRoute
  '/login': typeof GuestLoginRoute
  '/agent-teams/create': typeof AuthAgentTeamsCreateRoute
  '/agents/create': typeof AuthAgentsCreateRoute
  '/channels/create': typeof AuthChannelsCreateRoute
  '/providers/create': typeof AuthProvidersCreateRoute
  '/users/create': typeof AuthUsersCreateRoute
  '/agent-teams/': typeof AuthAgentTeamsIndexRoute
  '/agents/': typeof AuthAgentsIndexRoute
  '/channels/': typeof AuthChannelsIndexRoute
  '/providers/': typeof AuthProvidersIndexRoute
  '/roles/': typeof AuthRolesIndexRoute
  '/users/': typeof AuthUsersIndexRoute
  '/agent-teams/$teamId/edit': typeof AuthAgentTeamsTeamIdEditRoute
  '/agents/$agentId/edit': typeof AuthAgentsAgentIdEditRoute
  '/channels/$channelId/edit': typeof AuthChannelsChannelIdEditRoute
  '/llm/skills/create': typeof AuthLlmSkillsCreateRoute
  '/providers/$providerId/edit': typeof AuthProvidersProviderIdEditRoute
  '/users/$userId/edit': typeof AuthUsersUserIdEditRoute
  '/llm/skills/': typeof AuthLlmSkillsIndexRoute
  '/llm/skills/$skillId/edit': typeof AuthLlmSkillsSkillIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthDashboardRoute
  '/governance': typeof AuthGovernanceRoute
  '/tanstack-sse-test': typeof AuthTanstackSseTestRoute
  '/login': typeof GuestLoginRoute
  '/agent-teams/create': typeof AuthAgentTeamsCreateRoute
  '/agents/create': typeof AuthAgentsCreateRoute
  '/channels/create': typeof AuthChannelsCreateRoute
  '/providers/create': typeof AuthProvidersCreateRoute
  '/users/create': typeof AuthUsersCreateRoute
  '/agent-teams': typeof AuthAgentTeamsIndexRoute
  '/agents': typeof AuthAgentsIndexRoute
  '/channels': typeof AuthChannelsIndexRoute
  '/providers': typeof AuthProvidersIndexRoute
  '/roles': typeof AuthRolesIndexRoute
  '/users': typeof AuthUsersIndexRoute
  '/agent-teams/$teamId/edit': typeof AuthAgentTeamsTeamIdEditRoute
  '/agents/$agentId/edit': typeof AuthAgentsAgentIdEditRoute
  '/channels/$channelId/edit': typeof AuthChannelsChannelIdEditRoute
  '/llm/skills/create': typeof AuthLlmSkillsCreateRoute
  '/providers/$providerId/edit': typeof AuthProvidersProviderIdEditRoute
  '/users/$userId/edit': typeof AuthUsersUserIdEditRoute
  '/llm/skills': typeof AuthLlmSkillsIndexRoute
  '/llm/skills/$skillId/edit': typeof AuthLlmSkillsSkillIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/governance': typeof AuthGovernanceRoute
  '/_auth/tanstack-sse-test': typeof AuthTanstackSseTestRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_auth/agent-teams/create': typeof AuthAgentTeamsCreateRoute
  '/_auth/agents/create': typeof AuthAgentsCreateRoute
  '/_auth/channels/create': typeof AuthChannelsCreateRoute
  '/_auth/providers/create': typeof AuthProvidersCreateRoute
  '/_auth/users/create': typeof AuthUsersCreateRoute
  '/_auth/agent-teams/': typeof AuthAgentTeamsIndexRoute
  '/_auth/agents/': typeof AuthAgentsIndexRoute
  '/_auth/channels/': typeof AuthChannelsIndexRoute
  '/_auth/providers/': typeof AuthProvidersIndexRoute
  '/_auth/roles/': typeof AuthRolesIndexRoute
  '/_auth/users/': typeof AuthUsersIndexRoute
  '/_auth/agent-teams/$teamId/edit': typeof AuthAgentTeamsTeamIdEditRoute
  '/_auth/agents/$agentId/edit': typeof AuthAgentsAgentIdEditRoute
  '/_auth/channels/$channelId/edit': typeof AuthChannelsChannelIdEditRoute
  '/_auth/llm/skills/create': typeof AuthLlmSkillsCreateRoute
  '/_auth/providers/$providerId/edit': typeof AuthProvidersProviderIdEditRoute
  '/_auth/users/$userId/edit': typeof AuthUsersUserIdEditRoute
  '/_auth/llm/skills/': typeof AuthLlmSkillsIndexRoute
  '/_auth/llm/skills/$skillId/edit': typeof AuthLlmSkillsSkillIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/governance'
    | '/tanstack-sse-test'
    | '/login'
    | '/agent-teams/create'
    | '/agents/create'
    | '/channels/create'
    | '/providers/create'
    | '/users/create'
    | '/agent-teams/'
    | '/agents/'
    | '/channels/'
    | '/providers/'
    | '/roles/'
    | '/users/'
    | '/agent-teams/$teamId/edit'
    | '/agents/$agentId/edit'
    | '/channels/$channelId/edit'
    | '/llm/skills/create'
    | '/providers/$providerId/edit'
    | '/users/$userId/edit'
    | '/llm/skills/'
    | '/llm/skills/$skillId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/governance'
    | '/tanstack-sse-test'
    | '/login'
    | '/agent-teams/create'
    | '/agents/create'
    | '/channels/create'
    | '/providers/create'
    | '/users/create'
    | '/agent-teams'
    | '/agents'
    | '/channels'
    | '/providers'
    | '/roles'
    | '/users'
    | '/agent-teams/$teamId/edit'
    | '/agents/$agentId/edit'
    | '/channels/$channelId/edit'
    | '/llm/skills/create'
    | '/providers/$providerId/edit'
    | '/users/$userId/edit'
    | '/llm/skills'
    | '/llm/skills/$skillId/edit'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/_auth/dashboard'
    | '/_auth/governance'
    | '/_auth/tanstack-sse-test'
    | '/_guest/login'
    | '/_auth/agent-teams/create'
    | '/_auth/agents/create'
    | '/_auth/channels/create'
    | '/_auth/providers/create'
    | '/_auth/users/create'
    | '/_auth/agent-teams/'
    | '/_auth/agents/'
    | '/_auth/channels/'
    | '/_auth/providers/'
    | '/_auth/roles/'
    | '/_auth/users/'
    | '/_auth/agent-teams/$teamId/edit'
    | '/_auth/agents/$agentId/edit'
    | '/_auth/channels/$channelId/edit'
    | '/_auth/llm/skills/create'
    | '/_auth/providers/$providerId/edit'
    | '/_auth/users/$userId/edit'
    | '/_auth/llm/skills/'
    | '/_auth/llm/skills/$skillId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_auth/tanstack-sse-test': {
      id: '/_auth/tanstack-sse-test'
      path: '/tanstack-sse-test'
      fullPath: '/tanstack-sse-test'
      preLoaderRoute: typeof AuthTanstackSseTestRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/governance': {
      id: '/_auth/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof AuthGovernanceRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users/': {
      id: '/_auth/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthUsersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/roles/': {
      id: '/_auth/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof AuthRolesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/providers/': {
      id: '/_auth/providers/'
      path: '/providers'
      fullPath: '/providers/'
      preLoaderRoute: typeof AuthProvidersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/channels/': {
      id: '/_auth/channels/'
      path: '/channels'
      fullPath: '/channels/'
      preLoaderRoute: typeof AuthChannelsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/agents/': {
      id: '/_auth/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthAgentsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/agent-teams/': {
      id: '/_auth/agent-teams/'
      path: '/agent-teams'
      fullPath: '/agent-teams/'
      preLoaderRoute: typeof AuthAgentTeamsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users/create': {
      id: '/_auth/users/create'
      path: '/users/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof AuthUsersCreateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/providers/create': {
      id: '/_auth/providers/create'
      path: '/providers/create'
      fullPath: '/providers/create'
      preLoaderRoute: typeof AuthProvidersCreateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/channels/create': {
      id: '/_auth/channels/create'
      path: '/channels/create'
      fullPath: '/channels/create'
      preLoaderRoute: typeof AuthChannelsCreateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/agents/create': {
      id: '/_auth/agents/create'
      path: '/agents/create'
      fullPath: '/agents/create'
      preLoaderRoute: typeof AuthAgentsCreateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/agent-teams/create': {
      id: '/_auth/agent-teams/create'
      path: '/agent-teams/create'
      fullPath: '/agent-teams/create'
      preLoaderRoute: typeof AuthAgentTeamsCreateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/llm/skills/': {
      id: '/_auth/llm/skills/'
      path: '/llm/skills'
      fullPath: '/llm/skills/'
      preLoaderRoute: typeof AuthLlmSkillsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users/$userId/edit': {
      id: '/_auth/users/$userId/edit'
      path: '/users/$userId/edit'
      fullPath: '/users/$userId/edit'
      preLoaderRoute: typeof AuthUsersUserIdEditRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/providers/$providerId/edit': {
      id: '/_auth/providers/$providerId/edit'
      path: '/providers/$providerId/edit'
      fullPath: '/providers/$providerId/edit'
      preLoaderRoute: typeof AuthProvidersProviderIdEditRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/llm/skills/create': {
      id: '/_auth/llm/skills/create'
      path: '/llm/skills/create'
      fullPath: '/llm/skills/create'
      preLoaderRoute: typeof AuthLlmSkillsCreateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/channels/$channelId/edit': {
      id: '/_auth/channels/$channelId/edit'
      path: '/channels/$channelId/edit'
      fullPath: '/channels/$channelId/edit'
      preLoaderRoute: typeof AuthChannelsChannelIdEditRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/agents/$agentId/edit': {
      id: '/_auth/agents/$agentId/edit'
      path: '/agents/$agentId/edit'
      fullPath: '/agents/$agentId/edit'
      preLoaderRoute: typeof AuthAgentsAgentIdEditRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/agent-teams/$teamId/edit': {
      id: '/_auth/agent-teams/$teamId/edit'
      path: '/agent-teams/$teamId/edit'
      fullPath: '/agent-teams/$teamId/edit'
      preLoaderRoute: typeof AuthAgentTeamsTeamIdEditRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/llm/skills/$skillId/edit': {
      id: '/_auth/llm/skills/$skillId/edit'
      path: '/llm/skills/$skillId/edit'
      fullPath: '/llm/skills/$skillId/edit'
      preLoaderRoute: typeof AuthLlmSkillsSkillIdEditRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthGovernanceRoute: typeof AuthGovernanceRoute
  AuthTanstackSseTestRoute: typeof AuthTanstackSseTestRoute
  AuthAgentTeamsCreateRoute: typeof AuthAgentTeamsCreateRoute
  AuthAgentsCreateRoute: typeof AuthAgentsCreateRoute
  AuthChannelsCreateRoute: typeof AuthChannelsCreateRoute
  AuthProvidersCreateRoute: typeof AuthProvidersCreateRoute
  AuthUsersCreateRoute: typeof AuthUsersCreateRoute
  AuthAgentTeamsIndexRoute: typeof AuthAgentTeamsIndexRoute
  AuthAgentsIndexRoute: typeof AuthAgentsIndexRoute
  AuthChannelsIndexRoute: typeof AuthChannelsIndexRoute
  AuthProvidersIndexRoute: typeof AuthProvidersIndexRoute
  AuthRolesIndexRoute: typeof AuthRolesIndexRoute
  AuthUsersIndexRoute: typeof AuthUsersIndexRoute
  AuthAgentTeamsTeamIdEditRoute: typeof AuthAgentTeamsTeamIdEditRoute
  AuthAgentsAgentIdEditRoute: typeof AuthAgentsAgentIdEditRoute
  AuthChannelsChannelIdEditRoute: typeof AuthChannelsChannelIdEditRoute
  AuthLlmSkillsCreateRoute: typeof AuthLlmSkillsCreateRoute
  AuthProvidersProviderIdEditRoute: typeof AuthProvidersProviderIdEditRoute
  AuthUsersUserIdEditRoute: typeof AuthUsersUserIdEditRoute
  AuthLlmSkillsIndexRoute: typeof AuthLlmSkillsIndexRoute
  AuthLlmSkillsSkillIdEditRoute: typeof AuthLlmSkillsSkillIdEditRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthGovernanceRoute: AuthGovernanceRoute,
  AuthTanstackSseTestRoute: AuthTanstackSseTestRoute,
  AuthAgentTeamsCreateRoute: AuthAgentTeamsCreateRoute,
  AuthAgentsCreateRoute: AuthAgentsCreateRoute,
  AuthChannelsCreateRoute: AuthChannelsCreateRoute,
  AuthProvidersCreateRoute: AuthProvidersCreateRoute,
  AuthUsersCreateRoute: AuthUsersCreateRoute,
  AuthAgentTeamsIndexRoute: AuthAgentTeamsIndexRoute,
  AuthAgentsIndexRoute: AuthAgentsIndexRoute,
  AuthChannelsIndexRoute: AuthChannelsIndexRoute,
  AuthProvidersIndexRoute: AuthProvidersIndexRoute,
  AuthRolesIndexRoute: AuthRolesIndexRoute,
  AuthUsersIndexRoute: AuthUsersIndexRoute,
  AuthAgentTeamsTeamIdEditRoute: AuthAgentTeamsTeamIdEditRoute,
  AuthAgentsAgentIdEditRoute: AuthAgentsAgentIdEditRoute,
  AuthChannelsChannelIdEditRoute: AuthChannelsChannelIdEditRoute,
  AuthLlmSkillsCreateRoute: AuthLlmSkillsCreateRoute,
  AuthProvidersProviderIdEditRoute: AuthProvidersProviderIdEditRoute,
  AuthUsersUserIdEditRoute: AuthUsersUserIdEditRoute,
  AuthLlmSkillsIndexRoute: AuthLlmSkillsIndexRoute,
  AuthLlmSkillsSkillIdEditRoute: AuthLlmSkillsSkillIdEditRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface GuestRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
